### PR TITLE
feat: v2 of  git-worktree

### PR DESCRIPTION
**Pull request by polarmutex**
status:
- [x] git ops
    - [ ] has_branch testing
- [x] config
- [x] setup
- [x] switch worktree
- [x] create worktree
    - [ ] with origin setup
- [x] delete worktree
- [ ] documentation

### CODE REVIEW

**Comment by GitMurf** [comment]
Looking like great progress! Let me know when it’s ready to test and I can do a windows test!

**Comment by polarmutex** [comment]
think it is ready to start testing (most of the original features are in). need to spend time documenting and fine-tuning

**Comment by polarmutex** [comment]
definite bugs in creating worktrees that I need to look at

**Comment by GitMurf** [comment]
Yeah ran into some bugs but also wasn't sure if some of it was user error since I am new to git work tree stuff. Let me know when you feel like it is ready to test. Thanks!

**Comment by Dom324** [comment]
Just a fyi: I tried to play around with the `dev2` branch, and got fooled by the readme:
`:lua require('telescope').extensions.git_worktree.git_worktrees()`
But the real name of the function is `git_worktree()` :)
Is the telescope integration supposed to work?

**Comment by GitMurf** [comment]
@polarmutex it looks like you have been making some nice progress :) curious where things sit? is it ready for resting? thanks!

**Comment by polarmutex** [comment]
sorry have been really busy of late, but I think I have a good structure I like and going to clean but all the reported bugs and make a release

**Pull request merged**
